[build]
  command = "cd microfrontend-root/root-config && npm install && npm run build"
  publish = "microfrontend-root/root-config/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200