[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cliente"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/barbeiro"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login/*"
  to = "https://login-agend-barber.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cliente/*"
  to = "https://client-dashboard-mfe.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/barbeiro/*"
  to = "https://barber-dashboard-mfe.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200